[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tilegrab"
version = "0.1.0"
description = "Fast geospatial map tile downloader and mosaicker"
readme = "README.md"
authors = [{name = "Thiwa", email = "thiwanka.munasinghe@hotmail.com"}]
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]

dependencies = [
    "requests",
    "mercantile",
    "Pillow",
    "tqdm",
    "Box",
    "geopandas",
    "pyproj",
    "shapely"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock"
]

[project.scripts]
tilegrab = "tilegrab.cli:main"

[project.urls]
Homepage = "https://github.com/thiwaK/tilegrab"
